### PR TITLE
Components

### PR DESCRIPTION
**Pull request by Jagruti245**

### CODE REVIEW

**Review by dsquare0601 — CHANGES_REQUESTED** [review]
Department code only accept Numbers.

**Review by dsquare0601 — CHANGES_REQUESTED** [review]
1. Department Name only accept alphabets
2. Department_Attachment/Member : Filename Only accept alphabets
3. Attachment : CreatedAt & CreatedAtInt Not Required

**Comment by dsquare0601** [comment]
> Department code only accept Numbers.

**Review by dsquare0601 — APPROVED** [review]

**Review by TarushiJauhari — CHANGES_REQUESTED** [review]
1)Choose file placeholder is not there in attachment component
2)ssip attachment form does not contain bluecard

**Review by TarushiJauhari — APPROVED** [review]

**Pull request merged**
